### ISSUE TITLE
Self signed certificates

### ISSUE THREAD

**Issue by DoctorDimon** [actionhero/actionhero-node-client#24]
Hi!
I want to use TLS connections between AH instances and I use actionhero-node-client for connection. But I want to use internal Self signed certificates.
In current time, I cant pass options, especially `rejectUnauthorized: false` in `tls.connect` that located in `client.js`.

Can you please provide such ability?
Thank you!

**Comment by evantahler** [comment]
You can actually tell Node to ignore SSL errors with an environment variable, `NODE_TLS_REJECT_UNAUTHORIZED`.  Does this meet your needs?

**Comment by DoctorDimon** [comment]
Hi!
Actually yes, it does! I didn't know about this approach.
But maybe you think about me proposal to add options block.

Thank you!

**Comment by evantahler** [comment]
Frankly, I don't want to add any option which allows for /less/ security.  There are options which exist as a work-around, so I would prefer not to open that can of worms :D
