### ISSUE TITLE
Connection lost problem

### ISSUE THREAD

**Issue by DoctorDimon** [actionhero/actionhero-node-client#35]
Hello!

We have discovered problem with `actionhero-node-client` version `7.0.1` and above. When two services running ActionHero are started and one of them connected to another via `actionhero-node-client` all works fine.

If we restart `host` service, the client is not try to reconnect and just log timeout errors to log. Sometimes it logs `Not Connected` error to log but we have not saw any reconnect attempts.

With version `7.0.0` all works great!

`ActionHero 20.0.0`
`NodeJS 12.13.0`
`CentOS 7`

**Comment by evantahler** [comment]
Dang.

I think the only meaningful change between 7.0.0 and 7.0.1 can be seen here https://github.com/actionhero/actionhero-node-client/compare/v7.0.0...master#diff-50cfa59973c04321b5da0c6da0fdf4feR178-R181

this notion of `sending` was added to ensure that we can "linearly" set the `messageId` we want from the server before we start a new request (so you can't get a response back with the wrong message ID).  

It might be possible for the server to go down when `sending`, and we don't recover.  Can you add some logging to see if `sending` is true in your scenario?  Also, would you be able to write a test in this package or describe reproduction steps?

**Comment by evantahler** [comment]
Actually, this might be the solution for you: https://github.com/actionhero/actionhero-node-client/commit/45c0395f96fa8598d5bd8f05619d4ba6ca2f002a

1) if you weren't connected, we were still allowing `sending` to be marked as true
2) if something goes wrong with sending data and there was an exception, we would never revert to `sending=false`

**Comment by evantahler** [comment]
Let me know if that new commit fixes things for you, and I'll release a new version

**Comment by DoctorDimon** [comment]
Yes! With this commit everything seems to work fine! Service are stable like with version `7.0.0`

**Comment by DoctorDimon** [comment]
No... after time it appears again... When scheme is
`Node 1 (new code) -> Node 2 (new code) -> Node 3 (down)`

To serve request, `Node 2` should get data from `Node 3`, but it is down. With version `7.0.0` all is ok, it generate error and to ahead. When `Node 3` is up, it connects and all is OK.

With new code it works with first request and all next are freezes on `Node 2`. `Node 1` generates timeout errors for `Node 2` until `Node 2` will be rebooted.
